apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-antiaffinity-preferred
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: mylabel/database
              operator: In
              values:
              - mysql
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 80
  containers:
  - name: nginx
    image: nginx:latest
