apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-rolebinding-group
  namespace: default
subjects:
- kind: Group
  name: alicek106-org
roleRef:
  kind: Role
  name: service-reader 
  apiGroup: rbac.authorization.k8s.io
