apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-rolebinding-user
  namespace: default
subjects:
- kind: User
  name: alicek106-cert
roleRef:
  kind: Role
  name: service-reader 
  apiGroup: rbac.authorization.k8s.io
