apiVersion: v1
kind: Pod
metadata:
  name: completed-pod-restart-never
spec:
  restartPolicy: Never
  containers:
  - name: completed-pod-restart-never
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep 10 && exit 0"]
