apiVersion: v1
kind: Pod
metadata:
  name: error-pod-restart-never
spec:
  restartPolicy: Never
  containers:
  - name: error-pod-restart-never
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep 10 && exit 1"]
