apiVersion: v1
kind: Pod
metadata:
  name: poststart-hook
spec:
  containers:
  - name: poststart-hook
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["sh", "-c", "touch /myfile"]
