apiVersion: batch/v1
kind: Job
metadata:
  name: job-completions
spec:
  completions: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: busybox
        args: ["sh", "-c", "echo Hello, World && exit 0"]
        name: job-completions
