apiVersion: batch/v1
kind: Job
metadata:
  name: job-comple-parallel
spec:
  completions: 8
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: busybox
        args: ["sh", "-c", "echo Hello, World && exit 0"]
        name: job-comple-parallel
